# Vectors and Matrices in Numpy - Lab

## Introduction

This lab will ask you to perform some simple matrix creation and manipulation exercises based on what we have covered so far in this section. The key takeaway here for you is to be able to understand how to using indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays A (4x2) and B (2x3) 
```
A = 1402, 191 
    1371, 821 
    949, 1437
    147, 1448
    
B = 1, 2, 3
    4, 5, 6
    ```

In [1]:
import numpy as np

In [2]:
# Code Here
A = np.array([[1402, 191],[1371, 821],[949, 1437],[147, 1448]])

In [3]:
B = np.array([[1,2,3],[4,5,6]])

## 2. Print the dimensions of A and B 

In [4]:
|# Code Here
print("Shape of A: " + str(A.shape))

SyntaxError: invalid syntax (<ipython-input-4-0c42b7b41985>, line 1)

In [ ]:
# Code Here
print("Shape of B: " + str(B.shape))

## 3. Print some of the elements from A at following locations
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [5]:
# Code Here
print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A[3,0])


1402
191
1437
147


## 4. Write a routine to populate matrix with random data
* Create an 3x3 numpy array with all zeros (use `np.zeros()`)
* Access each location i,j of this matrix and fill in random values between the range 1 and 10. 

In [31]:
z = np.zeros((2,2))

len(z)

2

In [29]:
import numpy as np
np.random.seed(1111)

# Code Here (due to random data , your output might be different)
z_mat = np.zeros((3,3))
    
for r in range(3):
    for c in range(3):
        z_mat[r,c] = np.random.randint(1,10)

z_mat 

array([[8., 6., 2.],
       [3., 5., 9.],
       [7., 5., 9.]])

## 5. Turn above routine into a function.
* Create two 4x4 zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [37]:
# Code Here (due to random data , your output might be different)
z_mat_a = np.zeros((4,4))
z_mat_b = np.zeros((4,4))

def rando_matic(A,B):
    """
    Takes two nxn matrices, fills with random data and then returns
    the addition of the two
    
    Parameters
    ----------
    A: first matrix
    B: second matrix
    
    Returns
    -------
    result: matrix of same dimension as A and B
    """
    
    # Fill A and B with random ints
    # Assumes A and B have same square dimensions!
    for r in range(len(A)):
        for c in range(len(B)):
            A[r,c] = np.random.randint(1,10)
            B[r,c] = np.random.randint(1,10)
    
    # Add A and B
    result = A + B
    
    return A, B, result

D, E, rez = rando_matic(z_mat_a, z_mat_b)

print(D)
print(E)
print(rez)

[[6. 3. 9. 4.]
 [8. 4. 8. 1.]
 [3. 3. 6. 4.]
 [1. 8. 1. 8.]]
[[7. 3. 1. 2.]
 [7. 6. 1. 7.]
 [9. 9. 1. 7.]
 [4. 1. 9. 3.]]
[[13.  6. 10.  6.]
 [15. 10.  9.  8.]
 [12. 12.  7. 11.]
 [ 5.  9. 10. 11.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 